### ISSUE TITLE
使用Angular2+Nodejs实现文件上传能力

### ISSUE THREAD

**Issue by wenbaofu** [wenbaofu/blog#18]

**Comment by wenbaofu** [comment]
**计划实现以下能力**

- [ ] 寻找一个工具画出一个美观的文件上传的页面（UCD高保真）
- [ ] 使用Angular2重构它，抽象出一个组件，后续可以复用
- [ ] 后端使用NodeJS接收文件，并将页面描述写入JSON文件中
- [ ] 使用Angular2写个页面能够从JSON文件中重绘出页面

**Comment by wenbaofu** [comment]
> **寻找一个工具画出一个美观的文件上传的页面（UCD高保真）**

没有找到一个工具，但是找到了通过Bootstrap 3实现的封装好的文件上传组件
[bootstrap-fileinput ](https://github.com/kartik-v/bootstrap-fileinput)
[演示链接 ](http://www.jq22.com/demo/bootstrap-fileinput-master20161101/examples/)

- AJAX上传功能基于HTML5 FormData（绝大多数现代浏览器都支持该属性）。在不支持该属性的浏览器中会回退为普通的文件上传组件。使用AJAX必须设置uploadUrl属性。
- 允许你添加、移除和追加文件。添加的文件可以生成预览图。
- 可以将文件拖拽到指定区域来上传文件。
- 可以一个个的删除或更新文件，也可以同时完成这些操作。
- 如果showPreview属性设置为false，或者浏览器不支持uploadUrl属性，将会回退为普通的文件上传组件。
- 可以配置文件上传等待指示，文件上传成功信息，文件上传出错信息。
- 在使用ajax上传文件时可以添加额外的表单信息。
- 可以显示文件当前上传的进度。
- 可以取消和终止当前正在上传的任务。
- 文件上传完毕会自动刷新预览区域的内容。

**Comment by wenbaofu** [comment]
通过学习jquery发现通过可以获取拖拽到上传框中的信息
```
$("div[id^='preview-'][class='file-preview-frame kv-preview-thumb']")
```
下一步通过获取上传的内容信息构造表格，用于用户主动输入

**Comment by wenbaofu** [comment]
当前的能力如下动画
![upload](https://cloud.githubusercontent.com/assets/20511885/22343640/d5de8d5e-e433-11e6-9604-33a1e5665780.gif)

**Comment by wenbaofu** [comment]
测试发现一个问题，当上传失败后，删除文件，不能触发删除事件

**Comment by wenbaofu** [comment]
1. 使用express和nodejs搭建服务器，将index.html通过浏览器能够访问（怎么将现有的index.html直接发送给前端）
2. 给客户端反馈相关信息（需要查看相关的demo），使得上传组件的行为发生变更，进而发现文件上传的属性
3. 使用开源组件进行文件信息的分析，能够取出上传文件的信息
http://www.cnblogs.com/chyingp/p/express-multer-file-upload.html

**Comment by wenbaofu** [comment]
- [ ]  2. 将index.html通过浏览器能够访问,将现有的index.html直接发送给前端
两种方式
方式1：
```
res.sendfile('./index.html');
```
方式2：
```
  fs.readFile('./index.html', 'utf-8',function (err, data)
         {//读取内容
             if (err) throw err;
             res.writeHead(200, {"Content-Type": "text/html"});//注意这里
             res.write(data);
             res.end();
        });
```
但不管哪种都需要解决当客户端浏览器收到index.html后访问css和js资源的路径问题
它会直接访问http://127.0.0.1:3000/css/xx.css ,需要使用static方式将路径public化
[参考资料 path](http://javascript.ruanyifeng.com/nodejs/path.html)
[参考资料 static](http://expressjs.com/zh-cn/starter/static-files.html)

**Comment by wenbaofu** [comment]
- [ ] 设置上传组件的服务端路径的属性，使得能和服务端通信
[参考链接](http://plugins.krajee.com/file-input#ajax-uploads)
![image](https://cloud.githubusercontent.com/assets/20511885/22397273/104c9de8-e5a9-11e6-9340-9ed9ecdf7d8b.png)

**当服务端返回的消息没有错误的时候，客户端显示上传成功**
服务端代码
```
app.post('/file', function(req, res){
  var json = {};
  var str = JSON.stringify(json);
  res.send(str);
  
});
```
![image](https://cloud.githubusercontent.com/assets/20511885/22397300/6cb7e2cc-e5a9-11e6-877e-fa1c287b5cf3.png)
![image](https://cloud.githubusercontent.com/assets/20511885/22397283/339de14e-e5a9-11e6-87c0-3d91dc238c24.png)

**当服务端返回的消息有错误的时候，客户端能够将错误显示出来**

服务端代码
```
app.post('/file', function(req, res){
  var json = { error: '文件有问题' };
  var str = JSON.stringify(json);
  res.send(str);
  
});
```
![image](https://cloud.githubusercontent.com/assets/20511885/22397339/3e01a6d8-e5aa-11e6-88d1-328c9c22864d.png)
![image](https://cloud.githubusercontent.com/assets/20511885/22397347/5b2a643e-e5aa-11e6-92b8-91d7c1d410d5.png)

**Comment by wenbaofu** [comment]
- [ ] 4. 服务端能够解析上传的文件，并能根据文件后缀名保存到不同的文件夹

[npm scripts 书写指导](http://www.ruanyifeng.com/blog/2016/10/npm_scripts.html)
[使用mkdirp创建文件夹](http://stackoverflow.com/questions/39727920/cant-use-mkdir-in-npm-script-from-windows)


通过抓取上传组件的信息，能够发现一些报文信息，通过这些信息从网上查找相关的nodejs组件
![image](https://cloud.githubusercontent.com/assets/20511885/22397442/50b97b1e-e5ac-11e6-9270-14ca57e06fd7.png)
[引入开源组件multer](http://www.cnblogs.com/chyingp/p/express-multer-file-upload.html)
[使用指导](https://cnodejs.org/topic/564f32631986c7df7e92b0db)
[官方github](https://github.com/expressjs/multer)

记录上传的记录，引入log4js开源组件，用于日志记录
[参考实现](http://qianduan.guru/2016/08/21/nodejs-lesson-1-log4js/)
[参考实现](http://blog.fens.me/nodejs-log4js/)

**Comment by wenbaofu** [comment]
- [ ] 5. 将客户端的用户输入信息&用户电脑信息带到服务端，由服务端记录json文件

**Comment by wenbaofu** [comment]
:question: 异步debug如何进行

**Comment by wenbaofu** [comment]
:question: 两个异步的操作如何关联
一个操作只有先读出文件，处理后写入文件，同为异步操作，怎么写代码
```
var jsonData = req.body;
    jsonData["服务器存储文件名"] = req.file.filename;
        
    var jsonPath = path.resolve("./uploads/file.json");
    
    var storeJsonData;
    fs.readFile(jsonPath,function(err,data)
    {
        //当读取异常时，可能是文件不存在，设置初始状态
        if(!err)
        {
            storeJsonData = JSON.parse(data);
            logger.info("read " + jsonPath + " successfully:" + data);
            return;
        }

        if(err.code == 'ENOENT')
        {
            logger.error("read " + jsonPath + " error:" + err);
            storeJsonData = {"fileInfos":[]};
        }
        else
        {
            logger.error("read " + jsonPath + " error:" + err);
        }
    })
    
    storeJsonData.fileInfos.push(jsonData);
    fs.writeFile(jsonPath,JSON.stringify(storeJsonData),function(err)
    {
        if(err)
        {
            logger.error("write into " + jsonPath + " error:" + err);
        }
        else
        {
            logger.info("write into " + jsonPath + " successfully:" + JSON.stringify(storeJsonData));
        }
    });
```
报错如下：
![image](https://cloud.githubusercontent.com/assets/20511885/22405085/d972f96e-e677-11e6-855a-c9b25d4d2c5d.png)

**Comment by wenbaofu** [comment]
:question: **当批量上传时，出现服务器崩溃**

```
[0]
[0] SyntaxError: Unexpected token . in JSON at position 172
[0]     at Object.parse (native)
[0]     at F:\work\技能提升\upload\server\server.js:46:38
[0]     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
[0] node server.js exited with code 1

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! server@0.0.1 start: `concurrently "node server.js" `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@0.0.1 start script 'concurrently "node server.js" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "node server.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\work\技能提升\upload\server\npm-debug.log
```
![image](https://cloud.githubusercontent.com/assets/20511885/22406310/1f5f9540-e68c-11e6-8a41-c31f6ad5e568.png)

**Comment by wenbaofu** [comment]
通过分析业务场景发现：客户端传过来的信息+文件中的信息组合后写入文件中，存在文件异步操作的依赖
初步实现的代码如下：
```
function getFileContent(jsonPath,callback) { 
    setTimeout(function(){fs.readFile(jsonPath, function (err, data) {
            //当读取异常时，可能是文件不存在，设置初始状态
            var storeJsonData;
            if(!err)
            {
                storeJsonData = JSON.parse(data);
                logger.info("read " + jsonPath + " successfully:" + data);
                callback(storeJsonData);
                return;
            }

            if(err.code == 'ENOENT')
            {
                logger.error("read " + jsonPath + " error:" + err);
                storeJsonData = {"fileInfos":[]};
                callback(storeJsonData);
            }
            else
            {
                logger.error("read " + jsonPath + " error:" + err);
            }
        }
    )},5000);
    logger.info("setTimeout finish");
}


function saveData(jsonPath,req)
{
    getFileContent(jsonPath,function(data)
    {
        //将当前获取到的信息保存到读出来的信息中
        var jsonData = req.body;
        jsonData["服务器存储文件名"] = req.file.filename;
        data.fileInfos.push(jsonData);
        fs.writeFile(jsonPath,JSON.stringify(data),function(err)
        {
            if(err)
            {
                logger.error("write into " + jsonPath + " error:" + err);
            }
            else
            {
                logger.info("write into " + jsonPath + " successfully:" + JSON.stringify(data));
            }
        });
        logger.info("write file finish");
    });
}    
//获取客户端的信息并输出到json文件中

app.post('/file', function(req, res, next){
    var jsonPath = path.resolve("./uploads/file.json");
    saveData(jsonPath,req);
    next();
});
```
:question: 客户端不断的发消息过来，req变量也在不断的刷新，异步回调后拿到的req变量是什么值？
上下文会保存吗？

通过朴灵《深入浅出Node.js.pdf》关于请求对象的描述了解上下文信息都会保存，即使req对象没有在readfile和writefile的函数调用参数中
![image](https://cloud.githubusercontent.com/assets/20511885/22414997/ef3cdc9c-e6fe-11e6-83e3-1acc89fc0236.png)

**Comment by wenbaofu** [comment]
![image](https://cloud.githubusercontent.com/assets/20511885/22458493/b837fc8e-e7d7-11e6-8cbc-28bca88ac25d.png)
![image](https://cloud.githubusercontent.com/assets/20511885/22458517/cf73ec78-e7d7-11e6-9cf5-644d1bb71953.png)

[规避手段参考](http://stackoverflow.com/questions/28661281/add-object-to-json-file-node-js)

**Comment by wenbaofu** [comment]
> 使用Angular2写个页面能够从JSON文件中重绘出页面

先使用英雄模型的quickstart的案例作为参考，将index.html直接发送给客户端进行展示，测试成功

引入后出现了2个package.json文件，为了减少手工操作，需要在主json文件中能够调用第二个json的命令，用于代码的编译，监视代码变化等

引入pm2工具，相关[中文参考](http://www.cnblogs.com/zhoujie/p/nodejs4.html)
仅用在启动server.js 中，之前创建相关目录，以及启动其他目录的A2的package.json都还是用npm的能力

效果如下：
![image](https://cloud.githubusercontent.com/assets/20511885/22460591/834d7374-e7e0-11e6-8eee-e9845299750e.png)

**Comment by wenbaofu** [comment]
- [ ] 找一个视频网站的参考作为视频展示的一个页面组件的原型
[参考原型](http://www.mgtv.com/h/106700.html)
![image](https://cloud.githubusercontent.com/assets/20511885/22475626/823c3f76-e81a-11e6-94a4-775d698b3249.png)

按照播放次数可以搞个排行榜
![image](https://cloud.githubusercontent.com/assets/20511885/22463874/17a56dc0-e7ef-11e6-854b-29d7e0528787.png)

如果字数多可以做个收缩，展开的功能，[参考](http://codepen.io/CodingMonkeyzh/pen/Jdprxv)

**Comment by wenbaofu** [comment]
- [ ] 使用Angular2封装该组件，并使用独立的html和css文件，然后使用json数据能够在index页面中展示
:question: html和css文件独立后一堆问题，不能够正常展示

**Comment by wenbaofu** [comment]
暂时未找到合适的解决办法，在困惑中和Typescript的工程师交流，也未得到最后的结果，决定采用另外一种方式实现 [http RxJS方式](https://angular.cn/docs/ts/latest/guide/server-communication.html)

**Comment by wenbaofu** [comment]
但存在一个问题
:question: 每次file.json文件需要放在以根目录为起始的相关目录下，不然就会出现404错误
![image](https://cloud.githubusercontent.com/assets/20511885/22547270/e5521c18-e97b-11e6-860b-7a84aca5bb6f.png)
文件地址来自于 
```
private fileURL = "./app/file.json";
return this.http.get(this.fileURL).map(this.extractData).map(this.convertJsonToArray);
```
真实情况是file.json文件存在与一个和当前根目录不相关的目录中，目前的规避方法是先放在一个目录，
[相关参考](https://github.com/Microsoft/TypeScript/issues/5039)

**Comment by wenbaofu** [comment]
:question: 黄晓明_余文乐_阮经天-友情岁月(电影《血滴子》片尾曲).mp3 这种名字的话，会导致上传组件失效,走到如下逻辑，暂未定位
```
_resetFileStack: function () {
            var self = this, i = 0, newstack = [], newnames = [];
            self._getThumbs().each(function () {
                var $thumb = $(this), ind = $thumb.attr('data-fileindex'),
                    file = self.filestack[ind];
                if (ind === -1) {
                    return;
                }
                if (file !== undefined) {
                    newstack[i] = file;
                    newnames[i] = self._getFileName(file);
                    $thumb.attr({
                        'id': self.previewInitId + '-' + i,
                        'data-fileindex': i
                    });
                    i++;
                } else {
                    $thumb.attr({
                        'id': 'uploaded-' + uniqId(),
                        'data-fileindex': '-1'
                    });
                }
            });
```

**Comment by wenbaofu** [comment]
搜索框css的样式是取自百度首页
input和radio对齐，以及和周边最后采用
```
 margin-top: -6px;
    margin-right: 0px;
    margin-bottom: 0px;
    margin-left: 9px;
```

**Comment by wenbaofu** [comment]
:question: 使用service进行数据获取的时候存储在成员变量中，当再次获取时发现为空，猜测每次service执行不是单例模式

在找了大量的关于service单例的材料后发现一个结论：
> 1. 如果想用单例模式，将service注册在AppModule中所有组件共享即可
> 2. 如果想用私有模式，将service注册在组件的provider中

但是我的代码就是写成1这种方式，理论上应该是共享的单例模式，于是改用调试的方式观察原因，发现service的确只构造了一次，观察发现service的函数中的this指针有变化，第一次如下
![image](https://cloud.githubusercontent.com/assets/20511885/22597451/99d612a4-ea6a-11e6-988b-75d81c69d995.png)
是MapSubscriber构造的，但是第二次是object，是service构造的
![image](https://cloud.githubusercontent.com/assets/20511885/22597556/0ff4dda8-ea6b-11e6-98d6-fe3d5a5fac84.png)

于是怀疑是使用service的方式导致的，第一次调用是使用Observable，通过subscribe来获取的全量数据，同时将数据赋值给成员变量，第二次是普通方法，这时发现的数据为空。于是改查找 “observable angular2 cache” 来改造第二个方法。[相关参考](http://stackoverflow.com/questions/36271899/what-is-the-correct-way-to-share-the-result-of-an-angular-2-http-network-call-in)
```
export class DataService {
  private url:string = 'https://cors-test.appspot.com/test';

  private data: Data;
  private observable: Observable<any>;

  constructor(private http:Http) {}

  getData() {
    if(this.data) {
      // if `data` is available just return it as `Observable`
      return Observable.of(this.data); 
    } else if(this.observable) {
      // if `this.observable` is set then the request is in progress
      // return the `Observable` for the ongoing request
      return this.observable;
    } else {
      // example header (not necessary)
      let headers = new Headers();
      headers.append('Content-Type', 'application/json');
      // create the request, store the `Observable` for subsequent subscribers
      this.observable = this.http.get(this.url, {
        headers: headers
      })
      .map(response =>  {
        // when the cached data is available we don't need the `Observable` reference anymore
        this.observable = null;

        if(response.status == 400) {
          return "FAILURE";
        } else if(response.status == 200) {
          this.data = new Data(response.json());
          return this.data;
        }
        // make it shared so more than one subscriber can get the result
      })
      .share();
      return this.observable;
    }
  }
}
```

**Comment by wenbaofu** [comment]
> 由于keyup是每次输入后立刻响应，修改为输入完成后在进行搜索的能力

参考[官方文档](https://angular.cn/docs/ts/latest/guide/server-communication.html)
:question: 按照官方给出的指导，这样写，会导致初始化成功，但是按键不生效，如果后按键注册，则全部数据不能加载，怀疑这两个方法会出现覆盖，即一旦switchMap后，files就被赋值成空值
```

constructor(private fileservice : fileService)
    {
       this.files =  this.searchTermStream.debounceTime(300).distinctUntilChanged().
        switchMap(term => this.fileservice.getFiles(undefined,term));
        
    }

    ngOnInit() : void
    {
        this.fileservice.getFiles().subscribe(
                files => this.files = files,
            error => this.errorMessage = <any>error
        );
        
    }
```
:heavy_check_mark: 采用注册的方式解决的该问题，但是不确定是否最佳实践
```
constructor(private fileservice : fileService)
    {
        this.searchTermStream.debounceTime(300).distinctUntilChanged().
        switchMap(term => this.fileservice.getFiles(undefined,term)).subscribe(
            files => this.files = files
        );
        
    }

    ngOnInit() : void
    {
        this.fileservice.getFiles().subscribe(
                files => this.files = files,
            error => this.errorMessage = <any>error
        );
        
    }
```

**Comment by wenbaofu** [comment]
> 使用管道来过滤页面中的数据，达到筛选的目的
参考[官方文档](https://angular.cn/docs/ts/latest/guide/pipes.html)

**Comment by wenbaofu** [comment]
> 开始制作可以进行input输入参数过滤和radio过滤的pipe

从网上找到的已经制作好的[search pipe例子](https://plnkr.co/edit/WitglQDcZku4ZxHgi5yj?p=preview)

自制的可以自带[延时输入的input框](https://manuel-rauber.com/2015/12/31/debouncing-angular-2-input-component/)

**Comment by wenbaofu** [comment]
> 不同的文件类型在不同的页面中（页面标签），每种文件都能预览（pdf需要重新实现）

通过[ngSwitch](https://angular.cn/docs/ts/latest/guide/template-syntax.html#!#ngSwitch)实现不同的文件都能预览的能力

:heavy_check_mark: 两个注意点：
![image](https://cloud.githubusercontent.com/assets/20511885/22625553/1409c1fe-ebd5-11e6-91f0-ac9bd78f14b6.png)

embed元素，据说iframe元素也有这个问题,写法如下
```
<embed *ngSwitchCase="'pdf'" src="{{video.storeFileName}}" 
            class="kv-preview-data" width="100%" height="200" type="application/pdf"/>
```
报错如下
```
Error: unsafe value used in a resource URL context
at DomSanitizationServiceImpl.sanitize...
```
参考[网上的解决方案](https://plnkr.co/edit/ChdyzyPLxYqU94cVK9Qm?p=preview)

**Comment by wenbaofu** [comment]
> 为每个控件实现查看详情功能

![image](https://cloud.githubusercontent.com/assets/20511885/22626270/a59e52e2-ebe4-11e6-94cd-72370307bcb2.png)

通过调试[fileinput.js ](https://github.com/wenbaofu/blog/blob/master/upload/js/fileinput.js)的源码发现
[_initZoomButton](https://github.com/wenbaofu/blog/blob/master/upload/js/fileinput.js#L1371-L1379)为每个包含```kv-file-zoom```的元素都监听了鼠标的事件，当click事件发生时，执行```self._zoomPreview($el);```方法
